### ISSUE TITLE
页脚优化代码

### ISSUE THREAD

**Issue by yozman** [yozman/sysc#4]
相信大家都遇到过一个问题，
页面内容太少，
页脚不在浏览器底部，
显现出一段空白着实难看，
刚好折腾出 css 优化方案，
分享给大家：

```css
body {
    padding-bottom: [页脚高度]px;
}
footer {
    bottom: 0;
    height: [页脚高度]px;
    left: 0;
    position: absolute;
    right: 0;
}
html {
    min-height: 100%;
    position: relative;
}
```
